export const API_ENDPOINTS = [
  ['GET', '/api/health', 'Health check'],
  ['GET', '/api/status', 'Sync status'],
  ['GET', '/api/mappings/products', 'Product mappings'],
  ['GET', '/api/mappings/units', 'Unit mappings'],
  ['GET', '/api/conversions', 'Installed conversions, unit catalogs and products'],
  ['POST', '/api/conversions', 'Create a custom conversion'],
  ['DELETE', '/api/conversions/[id]', 'Delete a conversion and its inverse'],
  ['GET', '/api/conversions/library', 'Search the shared conversion library'],
  ['POST', '/api/conversions/preview', 'Preview a shared unit and conversion import'],
  ['POST', '/api/conversions/import', 'Apply a reviewed conversion import'],
  ['POST', '/api/sync/products', 'Trigger product sync'],
  ['POST', '/api/sync/grocy-to-mealie', 'Trigger Grocy to Mealie check'],
  ['POST', '/api/sync/grocy-to-mealie/ensure', 'Ensure below-min items on Mealie list'],
  ['POST', '/api/sync/grocy-to-mealie/in-possession', 'Reconcile Mealie in possession from Grocy stock'],
  ['POST', '/api/sync/mealie-to-grocy', 'Trigger Mealie to Grocy check'],
  ['POST', '/api/sync/shopping-cleanup', 'Run shopping list cleanup'],
  ['POST', '/api/sync/unlock', 'Clear scheduler and sync locks'],
  ['GET', '/api/plugins/installations', 'Shop plugin installations and connection status'],
  ['POST', '/api/plugins/installations', 'Create a shop plugin installation (token shown once)'],
  ['PATCH', '/api/plugins/installations/[id]', 'Rename a plugin installation or change its toggles'],
  ['DELETE', '/api/plugins/installations/[id]', 'Revoke a plugin installation'],
  ['POST', '/api/plugins/installations/[id]/rotate', 'Rotate a plugin token (shown once)'],
  ['POST', '/api/plugins/installations/[id]/auth', 'Relay a retailer sign-in step to the plugin'],
  ['POST', '/api/plugins/installations/[id]/reset-binding', 'Reset the retailer account and list binding'],
  ['GET', '/api/plugins/installations/[id]/catalog', 'Search the retailer catalogue through the plugin'],
  ['GET', '/api/shop/overview', 'Shared lists, receipts, review items and uncertain writes'],
  ['GET', '/api/shop/mappings', 'Retailer products, mappings and suggestions'],
  ['POST', '/api/shop/mappings', 'Create or replace a retailer product mapping'],
  ['PATCH', '/api/shop/mappings/[id]', 'Confirm a package amount or change the mapping role'],
  ['DELETE', '/api/shop/mappings/[id]', 'Delete a retailer product mapping'],
  ['POST', '/api/shop/suggestions/[id]', 'Accept or reject a mapping suggestion'],
  ['GET', '/api/shop/targets', 'Search Grocy products and Mealie foods to map to'],
  ['POST', '/api/shop/receipts/pull', 'Request a durable receipt pull'],
  ['POST', '/api/shop/run', 'Run the shared list sync now'],
  ['POST', '/api/shop/review/[lineId]', 'Substitute, dismiss or re-plan a receipt line under review'],
  ['POST', '/api/shop/effects/[id]', 'Decide a write whose outcome is unknown'],
  ['POST', '/api/shop/discrepancies/[id]', 'Resolve a stock discrepancy'],
  ['POST', '/api/shop/lines/resolve', 'Explain a paused shared-list line'],
] as const;
