services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - grocy_config:/config
    ports:
      - 9001:80
    restart: unless-stopped

  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    ports:
      - 9000:9000
    deploy:
      resources:
        limits:
          memory: 1000M #
    depends_on:
      - postgres
    volumes:
      - mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=http://mealie:9000
      - DB_ENGINE=postgres
      - POSTGRES_USER=mealie
      - POSTGRES_PASSWORD=F9EEoc6LqffjSYdaMCFq5d1PsNk61781
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mealie
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    volumes:
      - mealie-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=F9EEoc6LqffjSYdaMCFq5d1PsNk61781
      - POSTGRES_USER=mealie
volumes:
  grocy_config:
  mealie-data:
  mealie-pgdata:

networks:
  default:
    name: grocy-mealie-sync
    external: true
