/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum ExposedEntity {
    PRODUCTS = 'products',
    CHORES = 'chores',
    PRODUCT_BARCODES = 'product_barcodes',
    BATTERIES = 'batteries',
    LOCATIONS = 'locations',
    QUANTITY_UNITS = 'quantity_units',
    QUANTITY_UNIT_CONVERSIONS = 'quantity_unit_conversions',
    SHOPPING_LIST = 'shopping_list',
    SHOPPING_LISTS = 'shopping_lists',
    SHOPPING_LOCATIONS = 'shopping_locations',
    RECIPES = 'recipes',
    RECIPES_POS = 'recipes_pos',
    RECIPES_NESTINGS = 'recipes_nestings',
    TASKS = 'tasks',
    TASK_CATEGORIES = 'task_categories',
    PRODUCT_GROUPS = 'product_groups',
    EQUIPMENT = 'equipment',
    API_KEYS = 'api_keys',
    USERFIELDS = 'userfields',
    USERENTITIES = 'userentities',
    USEROBJECTS = 'userobjects',
    MEAL_PLAN = 'meal_plan',
    STOCK_LOG = 'stock_log',
    STOCK = 'stock',
    STOCK_CURRENT_LOCATIONS = 'stock_current_locations',
    CHORES_LOG = 'chores_log',
    MEAL_PLAN_SECTIONS = 'meal_plan_sections',
    PRODUCTS_LAST_PURCHASED = 'products_last_purchased',
    PRODUCTS_AVERAGE_PRICE = 'products_average_price',
    QUANTITY_UNIT_CONVERSIONS_RESOLVED = 'quantity_unit_conversions_resolved',
    RECIPES_POS_RESOLVED = 'recipes_pos_resolved',
    BATTERY_CHARGE_CYCLES = 'battery_charge_cycles',
    PRODUCT_BARCODES_VIEW = 'product_barcodes_view',
    PERMISSION_HIERARCHY = 'permission_hierarchy',
}
